### ISSUE TITLE
How to generate SQL dump for db-restore?

### ISSUE THREAD

**Issue by emjemj** [NORDUnet/ni#3]
Reading docker/db-restore.txt, you need a postgres.sql.gz to be able to ingest your data. how do I go about creating this, is it a simple pg_dump from my other installation or is there some script to produce it?

I figured out how to generate the json files but I can't import them without the SQL file.

**Comment by emjemj** [comment]
pg_dump -d norduni > postgres.sql did the trick.

**Comment by mkrogh** [comment]
Yep that is the way to do it. Checkout the src/scripts/backup dir as well.

--
Markus Krogh
